server {
    listen 80;
    server_name abhiyadav.in;

    location = /ichnos {
        return 301 /ichnos/;
    }

    location /ichnos/ {
        return 301 https://$host$request_uri;
    }
}

server {
    listen 443 ssl;
    server_name abhiyadav.in;

    ssl_certificate     /etc/letsencrypt/live/abhiyadav.in/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/abhiyadav.in/privkey.pem;

    location = /ichnos {
        return 301 /ichnos/;
    }

    location /ichnos/grafana/ {
        proxy_pass http://grafana:3000/;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Forwarded-Prefix /ichnos/grafana;
    }

    location /ichnos/ {
        proxy_pass http://api:8080/;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Forwarded-Prefix /ichnos;
    }
}
